language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: MGB9gxCTfpSzPHaByivo/K8J1M8FjevE9nh5DU1jFWQqukiNJq9sK2nZJE6ApAf+BEkXqRQvhAYqjnbgY/iRjL4fUFecaT3QdgnHA9UaM3jCUuisfF33z3F/RPlvZ+5h9yZI+M43FIQjiaF7dcB+t91h399kKrCeRueNm8dfH2oyCPYU5d850hS2zwv7ridte83Rmvixb6egkbQgS0EaMl72puMrnMAJKmDi9LHRXw9l5+t7sw29RNUwu7g/jk0mzKIzVwQMLhvjZu78LNgOz8p1HxuyGs5NdXE8FpcPjbtd+sx/lVPH/d1evq08EeR72NBRv0tRDbgp9L4ax8GRh9cUD8OWaU4po2IxTnk1Rchaj7fV6MKO9gb1wjrFNyhDSMSd1xN32qWh41mKJJ39qi2TecU3HX8HtYTnh7HB+NCBYmaiaAZ+tbW8qa38fSrSG27aw/hTL155ovsL/x6CK6NSGN38GOCK3n31kn+LfsNsB4QCAncKQ5eeghhCrKdA4QBmKGJERJm/rnhrwZNFyRvMUIkpB6vfgWsPyOn7hm75VZwna4OZ9vMa5SbKiHwEhe2bBCKubZ3d42lD3wak4COMCy4/xFQs5Y1Je65jU6doARTcPNxPwCKWADCW5m1bpEdhbD3hMhjRY/6uUWoP92D82GyDiDGCzdEAKDZfshI=
notifications:
  slack:
    secure: lfHunS4+moFMvT+pQi9ZKPBlvpVLdg/HUC33VmBMSdDfW8C4A/l58Jb3tubs/Z2hwWtudAbOS5TLPumGVhXawTCyxU3sanBIz5oM7Ym+vU97EgOTAoITPYdRxoVhDy+N6C175+KbeA9MjmdDwfo0hI7xqPD0lZJLiXVpRZ2bOidC7XyeEHDTgMZZ2+QKgf8Vb0kb5YeTKNF5OlU4slrzgGjXLiluZYnplNf3yeHj8/S4XCNcxI4Z66c6Nf/jcLnSN4NIMDYMKP20046ANIs7KIds4aJ5/Pax41kUuGZO+LKKgUzEL6T8rLKeGuoVgVxrjhuC8R7nPEo2CbK/agC92ucKFa2XACmmNTtBLob2e/IvG4AMFTT6XT3vOpcqbpGc/kSVmnHOev1WLTuRh420VYM6VmKKMw3SsFyrDIpSHBzmoQ+o0+YtHvVjMjwFpJou6Pa5vm3xBit1KnWM4WpPf/3eAnlS+pYJ4CrzS6rTnt75HzdwlH6L4rdV/SrDQkI11QjEug7omVklUFBWbR5pZEzC6xu+HXuj3njy6aMaODWsCaJNQF+dSrwoPq2ZtBoH75jrMvPOXFqRkVxjkhjVndfaDAkDZK95wFwDo3n9jyHL4yDljh21ZCLuoEpBJOhe1EO5tSMc8NJ08vsNcLGFMRy3mRueItvjj6vlkxX7Fo4=
