language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
env:
  global:
    secure: wcoDSYtRddeupOxYG6U/GyaczQki8NTNJgftQf2ruaG93fz8CXoRTCSwDxHyZg7or7obJQ7xWAkw0OHFf1cJl/mR80OHPOG3QJR0KH+vQpiFhEe42GMN2RCkqwpT2ZcUSeiZEd80MIddVEgOrKel3S/XaVutwYjg9c1pp8mPFI29VF+5jcKqSlUOrL5ADZ4nRAQgfM2mlDWNJ1g1+i0pvuFXQQbGAvpJVGXmy0Xt8RLgUFMWzwj34rqqJJkD1L9r3t56eHaISjcrtOj6gu1gpoUaP+oNAY2cJOdpyW4o2t/Cx7dDgjMu1uLCNhw+rLK7rzSJgjhtHoAGCOcVMqjmikeLGhRbl9SdhnJU2NpL63ifemSFRf7vB5puCbYNdkp8r7M/QAdMngH0+/mSU6rnn1hom2pnrNVtaHYHR5EK2fgmEWEf63wgUOZSdI3T2MSL67m1EWBsuV006G+4L0np4M8SGqdl5+f/suG3A6OZUMnuo493NMTjk6uozYvONRL2zaNX9Ie9lyBzuaWeT7GqFOUaj7bEF/pfCfO4pmVmdMoHzyLKlhwuW1SWpr7yIIBLUviGLqkofA8v61jtSv09og6ILCcZOUeCJ1Joy5YPolrgPhzPK5o08v/EVEscJtXT3gvU4gzzR3DU+5+GvNtJ/hY09PRO2Mn9qRcsVLJpJ6Y=
notifications:
  slack:
    secure: FlwAHJpd/3oO1VXRWRIrQx+RE4grvsm/EDG/G6xMBLkOyeMLz5nOOxUpxKudETpI6E2Z+LgQREDlIUHxVWGGeXLDgI2xbK7OhAS8PiYNsInGRrvEzLN5j1MV0j0BeiXpj+/19oRsmsU7sO2Lhw77mapXv9OASiFq8nGHdKL27LXbVmgeBUgWEnORiT5oRtBAFgkNJgSpZnVuBaNmoLzCX4m00fRA/B8If6YHUCzKjSqjmKN+6uedTCDs6vZPqbJo8NUHtjLnI5+ySDYbGxCHNqIG0Zv2Tkr9Bg5KkvUVV8dfg0B8v2q7SDy5ART1CtLMowKAJQ/c2MW1yhDYdYFBTbJHp1YkKQxvjgV8FXVZzA5NqHnU9D04QAZrC9Rim69HnKl5upU4KAHru/4jIRbEmlbmEmo3cLzg+FZpg417KOS4JPVTChJkzdfroP6sKI5JbWFtdN0fxCN5CpvSz90zjV4kAKp8kgc/nFNoOvbaZHwJLOpxLv02/hLjRvBHxIVstDqXuUQ2GXDIG8uDKZzc9ykGWiZZ/eAIRugSb9KJrM91RCttKcGR1P+3Yuy8bPA+EfeZ0wr2iiYJPtvboV6inJ3GriH/6bacVCDK17VOQhQgLaipgGWiuvfpPDcSs//wuEnZIhxA76cBO15LDZ1J6w73uehejLsZ05OYrsqLecc=
deploy:
- provider: npm
  api_key:
    secure: qeJAiaoYrUuPPIjpLJp4rztlbic9xPU7/bDCztb75BxoR7KjhN1r1p6s4TXitDGxP47FbS2bdV27zqNPV2EO+LLveUq58g6yLjRbUvFKwrYbE7VKQLHU6OctVPAfbzhGXCh7H9xh5jvoSXPU2ja+uJsxP/OgtO5m9DUoVH7xVvbcTbh8S7tU3bc99HkY3oMwms4F4ZUEwdC6tBKuQJd4Fq63F7vZsRl9kM9EACmFtIOkrBg+wEBiuwWVBb/XduPppvKHWCBOcLNof0eOJQDmqrdXBKDUhJtTK5C3vWcChrv3cREmgFYFVgg99PSuxFLvgHByGKztlA4FwgtqJaxcs9TQ6MpNOxAnY4VueWeuROSor2OXW1AODjCTkZW8qWErid0XPDPxBWWzwvRaf8p8DlSlMqSGvaITNX5kc6B7X7OsQNZmZP/ZZrTX38bftx54mbe1IfL3N5gG7vIwa58IP0iL8tuAfB1Zc6KxSclui+xLfgBz7PDye7yBkh99Mg1AtBxhv5EfZlDVdhqoKXYwiVhEk4W25PB+U6VIve3vTCoTR1/tCUHp8GceuxWMMRl6J8Q3aZJioRUD6eBTjNc8liEzozQO2uVq46dkMeWaKwzIIZm0F76FozmWSI/OLQj1Ewccm5s8Jzm4O6I7UgRi7UFwhYN0661A8Kbhop6yhpA=
  email:
    secure: brENT4F987ZoDfDEQSv0/TIwhVDvpggQAVJcgqAvbO/dfUhyMc7DUjhegikgUvkvI/wr57Zt8hGIYNilz1SA06uDGv0r8+UW+PEL5AGZhs3AkLO262lMCiZxZkwcYPVc96Ey8Ly1fHTGRyMEIcDj+XmP6eHvr/VCazxzbjxNmiyPmGvlP/V0uyf012fuOt6QxtN8OUkPaWTK2ebaGQKi/hxswTrKU7GCU1YnYc3Sdmfca/X/+aHcAuM6SMXtcmuJHY4erSUnJqSKtHsYP2iW5D2PZIiPS1YRwXB3gkYURfrasOKOgY3SkYWTs2W4WN7JePv5W4PVxPwE5mq3eo1cQ29iiFCPO8Lje1aqW/mwO43hV+ueU3CMzGrMPIC+8LDcZlTTny+x4DIumLVmpuwiQN/HrI/RRWcUkoNKUAleXjsVqkydxrY8e9fwpmpdei/94tnm2yOvcor3lPcdPXv8M+O7O0l8IG+RPU7Nym8B/LcgEBX0TQVbi81hgYEmC10rH3nccXrVyayZKPZbhZbVBulCtuBaXR3IrjssYDOa/Z/kzfjOHDLrYBhIQahEcxbwamdkhl+5MhZC+svizRfo4gG8FIh5ryHrhCD8JqAfqBrMnRTYJSX6EeG7zlOWF1sR3W0qlYQRov8ZvOKnECbffoqgD1q1lY37fyLCZEXq9oo=
  on:
    branch: master
