language: node_js
node_js:
- node
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: MGB9gxCTfpSzPHaByivo/K8J1M8FjevE9nh5DU1jFWQqukiNJq9sK2nZJE6ApAf+BEkXqRQvhAYqjnbgY/iRjL4fUFecaT3QdgnHA9UaM3jCUuisfF33z3F/RPlvZ+5h9yZI+M43FIQjiaF7dcB+t91h399kKrCeRueNm8dfH2oyCPYU5d850hS2zwv7ridte83Rmvixb6egkbQgS0EaMl72puMrnMAJKmDi9LHRXw9l5+t7sw29RNUwu7g/jk0mzKIzVwQMLhvjZu78LNgOz8p1HxuyGs5NdXE8FpcPjbtd+sx/lVPH/d1evq08EeR72NBRv0tRDbgp9L4ax8GRh9cUD8OWaU4po2IxTnk1Rchaj7fV6MKO9gb1wjrFNyhDSMSd1xN32qWh41mKJJ39qi2TecU3HX8HtYTnh7HB+NCBYmaiaAZ+tbW8qa38fSrSG27aw/hTL155ovsL/x6CK6NSGN38GOCK3n31kn+LfsNsB4QCAncKQ5eeghhCrKdA4QBmKGJERJm/rnhrwZNFyRvMUIkpB6vfgWsPyOn7hm75VZwna4OZ9vMa5SbKiHwEhe2bBCKubZ3d42lD3wak4COMCy4/xFQs5Y1Je65jU6doARTcPNxPwCKWADCW5m1bpEdhbD3hMhjRY/6uUWoP92D82GyDiDGCzdEAKDZfshI=
